export interface Employee {
    id: number;
    name: string;
    user_id: string | null;
    active: number;
    country_id: string | null;
    gender: string | null;
    marital: string | null;
    spouse_complete_name: string | null;
    spouse_birthdate: string | null;
    children: string | null;
    place_of_birth: string | null;
    country_of_birth: string | null;
    birthday: string | null;
    ssnid: string | null;
    identification_id: string | null;
    passport_id: string | null;
    bank_account_id: string | null;
    permit_no: string | null;
    visa_no: string | null;
    visa_expire: string | null;
    additional_note: string | null;
    certificate: string | null;
    study_field: string | null;
    study_school: string | null;
    emergency_contact: string | null;
    emergency_phone: string | null;
    notes: string | null;
    barcode: string | null;
    pin: string | null;
    departure_reason: string | null;
    departure_description: string | null;
    department_id: string | null;
    job_id: string | null;
    company_id: string | null;
    address: string | null;
    street: string | null;
    street2: string | null;
    zip: string | null;
    city: string | null;
    state_id: string | null;
    work_phone: string | null;
    mobile_phone: string | null;
    work_email: string | null;
    work_location: string | null;
    photo: string | null;
    salary: string | null;
    parent_id: string | null;
    coach_id: string | null;
    currency_id: string | null;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    nationality: string | null;
    image: string | null;
    empid: string;
    dob: string;
    doj: string;
    department: string;
    designation: string;
    email: string;
    phone: string;
    username: string;
}